name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8
    - name: Lint with isort
      run: |
        pipenv run isort -c
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=doccano_transformer tests
